simulator : 
  folder : "two_lane"
  dt : 1 
  total_time : 1000
  seed : 1
  quick_mode : 0
  evaluation :
    dt : 10
    queue_length : "off"
    delay_time : "on"
    calc_time : "off"
  save : 
    performance_indicators: "on"
    

mpc :
  dt : 2
  N_p : 4
  N_c : 2
  D_o : 100

scoot : 
  ds : 4
  cycle : 60
  alpha : 0.8
  beta : 0.2

  